### ISSUE TITLE
Why is the text so blurry?

### ISSUE THREAD

**Issue by kolva3** [bituq/Roshade#4]
So I came back to Roshade after a couple of months and reinstalled it. Only problem I have with it is the blurry text.
Version 1.22 (new)
![Capture](https://user-images.githubusercontent.com/83851584/124051508-27f89f80-da0c-11eb-8fdb-c0485143b152.PNG)
Version 1.36 (old)
![Capture2](https://user-images.githubusercontent.com/83851584/124051634-5fffe280-da0c-11eb-8399-0b5b56600ee6.PNG)
I don't know if you notice it or if it's just me.

**Comment by bituq** [comment]
Hey kolva3,
This is actually related to an issue in the font. I changed the default font for Roshade to Open Sans, which required the text to be upscaled. Once it gets upscaled, the text might get blurry. However, the issue is that the file path to the fonts was wrong, so it shows the old font, which is blurry.

Install the latest version of Roshade and this issue should be fixed.

**Comment by kolva3** [comment]
ok, it's no longer blurry, closing.
